name: 'Run tests'

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
      - develop
      - storybook
    # paths:
    #   - 'src/**/*.js'
    #   - 'src/**/*.scss'
    #   - 'tests/**/*.js'

jobs:

  # https://github.com/actions/setup-node#caching-global-packages-data
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Cache .npm directory
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  # visual-regression:
  #   name: Run visual regression tests
  #   runs-on: ubuntu-latest
  #   needs: install-cache
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run Chromatic
  #       uses: chromaui/action@latest
  #       with:
  #         projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  #         onlyChanged: true
