name: Deploy to GitHub Pages

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [Run tests]
    branches:
      - main
      - develop
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    environment: 'github-pages'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Build and publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          checkout: false
          path: 'storybook-static'
          build_command: 'npm run build-storybook-docs'
