name: Deploy to GitHub Pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run tests
    uses: johnshopkins/jhu-wds-experimenting/.github/workflows/tests.yaml@main
    
  deploy:
    runs-on: ubuntu-latest
    environment: 'github-pages'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          checkout: false
          path: 'storybook-static'
          build_command: 'npm run build-storybook-docs'
