name: Prepare release

on:
  push:
    branches:
      - 'release-**'
      - 'patch-**'

jobs:
  branch-checks:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ tojson(github) }}
        shell: cat {0}
#       - id: get-branch
#         run: |
#           BRANCH=($(echo ${{ github.ref }} | sed -E 's/refs\/heads\///'))
#           echo "branch=$BRANCH" >> $GITHUB_ENV
#     outputs:
#       branch: ${{ env.branch }}
#       is-latest-branch: ${{ env.branch == 'main' }}
#       is-next-branch: ${{ env.branch == 'next' }}
#       is-release-branch: ${{ startsWith(env.branch, 'release-') }}
#       is-actionable-branch: ${{ env.branch == 'main' || env.branch == 'next' || startsWith(env.branch, 'release-') }}

#   open-pull-request:
#     runs-on: ubuntu-latest
#     steps:
#       - run: gh pr create
#         env:
#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           ISSUE: ${{ github.event.issue.html_url }}
