name: Run tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      # - name: Get Playwright version
      #   run: echo "version=$(npx playwright --version | sed 's/Version //')" >> $GITHUB_OUTPUT
      #   id: playwright-version

      # - uses: actions/cache@v4
      #   id: playwright-cache
      #   with:
      #     path: ~/.cache/ms-playwright
      #     key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
      #     restore-keys: |
      #       ${{ runner.os }}-playwright-

      # - name: Install Playwright Browsers
      #   if: steps.playwright-cache.outputs.cache-hit != 'true'
      #   run: npx playwright install --with-deps

      - name: Run tests
        run: npm test
